# 🧩 Reto 2 – pH
**Objetivo:** clasificar pH y generar alerta química.

**Datos:** `../data/muestras_calidad_agua.csv`

### Pasos
1. Carga el CSV en `df`.
2. Extrae `sitio` y `pH`.
3. Crea `clasificacion_pH` con tres rangos.
4. Crea `alerta_quimica` (revisión si pH < 6.5 o pH > 8.5).
5. Filtra `df_alerta` y exporta `resultado_ph.csv`.

> **Reto adicional:** promedio y desviación estándar.

In [1]:
1# Carga el CSV en df
import pandas as pd


df = pd.read_csv("../data/muestras_calidad_agua.csv")

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sitio        10 non-null     str
 1   pH           10 non-null     float64
 2   oxigeno      10 non-null     float64
 3   temperatura  10 non-null     float64
dtypes: float64(3), str(1)
memory usage: 452.0 bytes

In [2]:
2# Extraer sitio y pH df_pH

df_pH = df[["sitio", "pH"]]

df_pH

                           sitio   pH
0                 Río Subachoque  7.2
1    Quebrada Honda (Facatativá)  6.3
2           Río Botello (Madrid)  6.8
3   Afluente San José (El Rosal)  7.9
4                    Río Villeta  8.7
5  Quebrada Cune (San Francisco)  6.0
6            Río Tobia (Nocaima)  7.4
7       Quebrada Negra (La Vega)  7.6
8          Río Bahamón (Sasaima)  8.1
9        Río Guayuriba (La Mesa)  5.9

In [6]:
3# Crea clasificacion_pH con tres rangos.

import numpy as np

df_pH["clasificacion_pH"] = np.where(
    df_pH["pH"] < 6.5,
    "Ácido",
    np.where(
        df_pH["pH"] <= 8.5,
        "Neutro",
        "Básico"
    )
)

df_pH

                           sitio   pH clasificacion_pH
0                 Río Subachoque  7.2           Neutro
1    Quebrada Honda (Facatativá)  6.3            Ácido
2           Río Botello (Madrid)  6.8           Neutro
3   Afluente San José (El Rosal)  7.9           Neutro
4                    Río Villeta  8.7           Básico
5  Quebrada Cune (San Francisco)  6.0            Ácido
6            Río Tobia (Nocaima)  7.4           Neutro
7       Quebrada Negra (La Vega)  7.6           Neutro
8          Río Bahamón (Sasaima)  8.1           Neutro
9        Río Guayuriba (La Mesa)  5.9            Ácido

In [7]:
4# Crea alerta_quimica (revisión si pH < 6.5 o pH > 8.5)
def alerta(ph):
    if ph < 6.5 or ph > 8.5:
        return "Sí"
    else:
        return "No"

df_pH["alerta_quimica"] = df_pH["pH"].apply(alerta)

df_pH

                           sitio   pH clasificacion_pH alerta_quimica
0                 Río Subachoque  7.2           Neutro             No
1    Quebrada Honda (Facatativá)  6.3            Ácido             Sí
2           Río Botello (Madrid)  6.8           Neutro             No
3   Afluente San José (El Rosal)  7.9           Neutro             No
4                    Río Villeta  8.7           Básico             Sí
5  Quebrada Cune (San Francisco)  6.0            Ácido             Sí
6            Río Tobia (Nocaima)  7.4           Neutro             No
7       Quebrada Negra (La Vega)  7.6           Neutro             No
8          Río Bahamón (Sasaima)  8.1           Neutro             No
9        Río Guayuriba (La Mesa)  5.9            Ácido             Sí

In [ ]:
5# Filtra df_alerta y exporta resultado_ph.csv

In [9]:
df_alerta = df_pH[df_pH["alerta_quimica"] == "Sí"]

df_alerta

                           sitio   pH clasificacion_pH alerta_quimica
1    Quebrada Honda (Facatativá)  6.3            Ácido             Sí
4                    Río Villeta  8.7           Básico             Sí
5  Quebrada Cune (San Francisco)  6.0            Ácido             Sí
9        Río Guayuriba (La Mesa)  5.9            Ácido             Sí

In [10]:
df_alerta.to_csv("resultado_ph.csv", index=False)

In [16]:
##RETO ADICIONAL
#Reto adicional:promedio y desviación estándar.
promedio = df_pH["pH"].mean()

print("Promedio de pH:", promedio)


desviacion = df_pH["pH"].std()

print("Desviación estándar:", desviacion)

Promedio de pH: 7.19
Desviación estándar: 0.9338688939626969