# 🧩 Reto 1 – Temperatura
**Objetivo:** clasificar la temperatura del agua y evaluar posible estrés térmico.

**Datos:** `../data/muestras_calidad_agua.csv`

### Pasos
1. Carga el CSV en `df`.
2. Extrae `sitio` y `temperatura` en `df_temp`.
3. Crea `categoria_temp` con np.where o .loc.
4. Crea `riesgo_termico`.
5. Filtra a `df_caliente` (alta temperatura).
6. Exporta `resultado_temperatura.csv`.

> **Reto adicional:** porcentaje de sitios con riesgo térmico.

In [6]:
1# Carga el CSV en df
import pandas as pd


df = pd.read_csv("../data/muestras_calidad_agua.csv")

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sitio        10 non-null     str
 1   pH           10 non-null     float64
 2   oxigeno      10 non-null     float64
 3   temperatura  10 non-null     float64
dtypes: float64(3), str(1)
memory usage: 452.0 bytes

In [7]:
2# Extraer sitio y temperatura en df_temp

df_temp = df[["sitio", "temperatura"]]

df_temp

                           sitio  temperatura
0                 Río Subachoque         18.5
1    Quebrada Honda (Facatativá)         19.4
2           Río Botello (Madrid)         22.7
3   Afluente San José (El Rosal)         20.1
4                    Río Villeta         28.3
5  Quebrada Cune (San Francisco)         25.2
6            Río Tobia (Nocaima)         26.9
7       Quebrada Negra (La Vega)         24.4
8          Río Bahamón (Sasaima)         27.6
9        Río Guayuriba (La Mesa)         30.5

In [8]:
3# Crear categoria_temp con np.where o loc

import numpy as np

df_temp["categoria_temp"] = np.where(
    df_temp["temperatura"] < 20,
    "Fría",
    np.where(
        df_temp["temperatura"] <= 26,
        "Moderada",
        "Alta"
    )
)

df_temp

                           sitio  temperatura categoria_temp
0                 Río Subachoque         18.5           Fría
1    Quebrada Honda (Facatativá)         19.4           Fría
2           Río Botello (Madrid)         22.7       Moderada
3   Afluente San José (El Rosal)         20.1       Moderada
4                    Río Villeta         28.3           Alta
5  Quebrada Cune (San Francisco)         25.2       Moderada
6            Río Tobia (Nocaima)         26.9           Alta
7       Quebrada Negra (La Vega)         24.4       Moderada
8          Río Bahamón (Sasaima)         27.6           Alta
9        Río Guayuriba (La Mesa)         30.5           Alta

In [9]:
4# Crear riesgo_termico  se tiene en cuent a mque solo es riego cuando la temperatura es alta 

df_temp["riesgo_termico"] = np.where(
    df_temp["categoria_temp"] =="Alta",
    "Sí",
    "No"
)

df_temp

                           sitio  temperatura categoria_temp riesgo_termico
0                 Río Subachoque         18.5           Fría             No
1    Quebrada Honda (Facatativá)         19.4           Fría             No
2           Río Botello (Madrid)         22.7       Moderada             No
3   Afluente San José (El Rosal)         20.1       Moderada             No
4                    Río Villeta         28.3           Alta             Sí
5  Quebrada Cune (San Francisco)         25.2       Moderada             No
6            Río Tobia (Nocaima)         26.9           Alta             Sí
7       Quebrada Negra (La Vega)         24.4       Moderada             No
8          Río Bahamón (Sasaima)         27.6           Alta             Sí
9        Río Guayuriba (La Mesa)         30.5           Alta             Sí

In [10]:
5# Filtrar a df_caliente 
df_caliente = df_temp[df_temp["categoria_temp"] == "Alta"]

df_caliente

                     sitio  temperatura categoria_temp riesgo_termico
4              Río Villeta         28.3           Alta             Sí
6      Río Tobia (Nocaima)         26.9           Alta             Sí
8    Río Bahamón (Sasaima)         27.6           Alta             Sí
9  Río Guayuriba (La Mesa)         30.5           Alta             Sí

In [11]:
6#Exporta resultado_temperatura.csv

df_temp.to_csv("resultado_temperatura.csv")