# 🧩 Reto 3 – Oxígeno disuelto
**Objetivo:** evaluar riesgo ecológico según oxígeno disuelto.

**Datos:** `../data/muestras_calidad_agua.csv`

### Pasos
1. Carga el CSV en `df`.
2. Extrae `sitio` y `oxigeno`.
3. Crea `nivel_oxigeno` (bajo/medio/alto).
4. Crea `riesgo_biologico` (⚠ si oxígeno < 5).
5. Filtra y exporta `resultado_oxigeno.csv`.

> **Reto adicional:** porcentaje de sitios con riesgo.

In [30]:
df

                           sitio   pH  oxigeno  temperatura
0                 Río Subachoque  7.2      7.8         18.5
1    Quebrada Honda (Facatativá)  6.3      6.2         19.4
2           Río Botello (Madrid)  6.8      5.9         22.7
3   Afluente San José (El Rosal)  7.9      8.3         20.1
4                    Río Villeta  8.7      6.1         28.3
5  Quebrada Cune (San Francisco)  6.0      4.5         25.2
6            Río Tobia (Nocaima)  7.4      5.2         26.9
7       Quebrada Negra (La Vega)  7.6      7.0         24.4
8          Río Bahamón (Sasaima)  8.1      6.7         27.6
9        Río Guayuriba (La Mesa)  5.9      4.8         30.5

In [31]:
import pandas as pd

In [32]:
df.columns

Index(['sitio', 'pH', 'oxigeno', 'temperatura'], dtype='str')

In [35]:
oxigeno = df[["sitio", "oxigeno"]]

oxigeno

                           sitio  oxigeno
0                 Río Subachoque      7.8
1    Quebrada Honda (Facatativá)      6.2
2           Río Botello (Madrid)      5.9
3   Afluente San José (El Rosal)      8.3
4                    Río Villeta      6.1
5  Quebrada Cune (San Francisco)      4.5
6            Río Tobia (Nocaima)      5.2
7       Quebrada Negra (La Vega)      7.0
8          Río Bahamón (Sasaima)      6.7
9        Río Guayuriba (La Mesa)      4.8

In [36]:
def clasificar_oxigeno(valor):

    if valor < 5:
        return "bajo"

    elif valor <= 7:
        return "medio"

    else:
        return "alto"

In [37]:
oxigeno["nivel_oxigeno"] = oxigeno["oxigeno"].apply(clasificar_oxigeno)

oxigeno

                           sitio  oxigeno nivel_oxigeno
0                 Río Subachoque      7.8          alto
1    Quebrada Honda (Facatativá)      6.2         medio
2           Río Botello (Madrid)      5.9         medio
3   Afluente San José (El Rosal)      8.3          alto
4                    Río Villeta      6.1         medio
5  Quebrada Cune (San Francisco)      4.5          bajo
6            Río Tobia (Nocaima)      5.2         medio
7       Quebrada Negra (La Vega)      7.0         medio
8          Río Bahamón (Sasaima)      6.7         medio
9        Río Guayuriba (La Mesa)      4.8          bajo

In [ ]:
# Escribe tu código aquí
df = pd.read_csv("../data/muestras_calidad_agua.csv")