# 🧩 Reto 4 – Integración de resultados
**Objetivo:** combinar resultados parciales en un diagnóstico integral por sitio.

# Reto 4 – Integración de resultados

En este notebook se integran los resultados de temperatura, pH y oxígeno para generar un diagnóstico final de calidad del agua en diferentes sitios de Cundinamarca.

### Pasos
1. Carga `resultado_temperatura.csv`, `resultado_ph.csv`, `resultado_oxigeno.csv`.
2. Únelos por `sitio` usando `merge`.
3. Crea `diagnostico_final` con reglas (parcial/total/normal).
4. Exporta `diagnostico_final.csv`.
5. Cuenta categorías con `value_counts()`.

> **Reto adicional:** gráfico de barras de distribución.

In [5]:
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
temp = pd.read_csv("../data/resultado_temperatura.csv")
ph = pd.read_csv("../data/resultado_ph.csv")
ox = pd.read_csv("../data/resultado_oxigeno.csv")

In [10]:
temp.head()

,Unnamed: 0,sitio,temperatura,categoria_temp,riesgo_termico
0,0,Río Subachoque,18.5,Fría,No
1,1,Quebrada Honda (Facatativá),19.4,Fría,No
2,2,Río Botello (Madrid),22.7,Moderada,No
3,3,Afluente San José (El Rosal),20.1,Moderada,No
4,4,Río Villeta,28.3,Alta,Sí

In [11]:
ph.head()

                           sitio   pH clasificacion_pH alerta_quimica
0    Quebrada Honda (Facatativá)  6.3            Ácido             Sí
1                    Río Villeta  8.7           Básico             Sí
2  Quebrada Cune (San Francisco)  6.0            Ácido             Sí
3        Río Guayuriba (La Mesa)  5.9            Ácido             Sí

In [12]:
ox.head()

                          sitio  oxigeno nivel_oxigeno riesgo_biologico
0                Río Subachoque      7.8          alto       Sin riesgo
1   Quebrada Honda (Facatativá)      6.2         medio       Sin riesgo
2          Río Botello (Madrid)      5.9         medio       Sin riesgo
3  Afluente San José (El Rosal)      8.3          alto       Sin riesgo
4                   Río Villeta      6.1         medio       Sin riesgo

In [13]:
datos = pd.merge(temp, ph, on="sitio")
datos = pd.merge(datos, ox, on="sitio")

In [14]:
datos.head()

,Unnamed: 0,sitio,temperatura,categoria_temp,riesgo_termico,pH,clasificacion_pH,alerta_quimica,oxigeno,nivel_oxigeno,riesgo_biologico
0,1,Quebrada Honda (Facatativá),19.4,Fría,No,6.3,Ácido,Sí,6.2,medio,Sin riesgo
1,4,Río Villeta,28.3,Alta,Sí,8.7,Básico,Sí,6.1,medio,Sin riesgo
2,5,Quebrada Cune (San Francisco),25.2,Moderada,No,6.0,Ácido,Sí,4.5,bajo,⚠ Riesgo biológico
3,9,Río Guayuriba (La Mesa),30.5,Alta,Sí,5.9,Ácido,Sí,4.8,bajo,⚠ Riesgo biológico

In [15]:
datos["diagnostico_final"] = "Normal"

In [20]:
datos.loc[
    (datos["oxigeno"] < 5),
    "diagnostico_final"
] = "Parcial"

In [ ]:
datos.loc[
    (datos["oxigeno"] < 5) &
    (datos["temperatura_°C"] > 28),
    "diagnostico_final"
] = "Total"